services:
  vd-gui:
    image: ghcr.io/verus-datum/gui:latest
    build:
      context: .
      dockerfile: deploy/gui/Dockerfile
    container_name: vd-gui
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=https://vd.harville.dev/api:8081

  vd-api:
    image: ghcr.io/verus-datum/api:latest
    build:
      context: .
      dockerfile: deploy/api/Dockerfile
    container_name: vd-api
    ports:
      - 8081:8081
    environment:
      - VITE_API_URL=https://vd.harville.dev/api:8081
