

gui:
  image:
    repository: ghcr.io/verus-datum/gui
    tag: latest
  replicaCount: 2
  port: 3000
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

api:
  image:
    repository: ghcr.io/verus-datum/api
    tag: latest
  replicaCount: 2
  port: 8081
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

postgresql:
  enabled: true
  auth:
    username: admin
    password: password
    database: vd_db
  primary:
    persistence:
      size: 8Gi
  replication:
    enabled: true
    replicaCount: 2

postgresqlHPA:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
