apiVersion: v1
kind: Service
metadata:
  name: {{ include "vd.fullname" . }}-api
  labels: {{- include "vd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  selector:
    app.kubernetes.io/name: {{ include "vd.name" . }}
    component: api
