apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vd.fullname" . }}-gui
  labels:
    {{- include "vd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gui.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vd.name" . }}
      component: gui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vd.name" . }}
        component: gui
    spec:
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecret }}
      containers:
        - name: gui
          image: "{{ .Values.gui.image.repository }}:{{ .Values.gui.image.tag }}"
          env:
{{ toYaml .Values.gui.env | indent 12 }}
          ports:
            - containerPort: {{ .Values.gui.port }}
