apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vd.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "vd.name" . }}
    component: db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vd.name" . }}
      component: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vd.name" . }}
        component: db
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: {{ include "vd.fullname" . }}-db-data
      containers:
      - name: db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.db.port }}
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.db.env.POSTGRES_USER | default "admin" }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.db.env.POSTGRES_PASSWORD | default "password" }}"
        - name: POSTGRES_DB
          value: "{{ .Values.db.env.POSTGRES_DB | default "vd_db" }}"

