apiVersion: v1
kind: Service
metadata:
  name: {{ include "vd.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "vd.name" . }}
    component: db
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "vd.name" . }}
    component: db
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}

