name: Build & Push Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0        # need all commits
          fetch-tags: true      # need existing 0.0.* tags
          token: ${{ secrets.PAT_TOKEN }}

      - name: Bump patch version
        id: bump
        run: |
          # find latest 0.0.* tag
          LAST=$(git tag --list '0.0.*' --sort=-v:refname | head -n1)
          if [ -z "$LAST" ]; then
            NEXT="0.0.1"
          else
            P=${LAST##*.}
            NEXT="0.0.$((P+1))"
          fi
          echo "IMAGE_TAG=$NEXT" >> $GITHUB_ENV

          git tag "$NEXT"
          git push origin "$NEXT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Images
        run: docker compose build --push
